version: "3"
services:
    webserver:
        image: webdevops/apache:alpine
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - "./public_html:/var/www/html"
        environment:
            WEB_DOCUMENT_ROOT: "/var/www/html"
volumes:
    data: